### ISSUE TITLE
New Rule: Ensure that all KMS delete wait periods are at least 30 days (or X days)

### ISSUE THREAD

**Issue by 0xjjoyy** [awslabs/aws-config-rules#144]
Use case is to ensure that all KMS keys that have configured a delete wait period must have a sufficiently long enough wait period. The time period should configurable and be above the threshold defined by the company policy, for example 30 days.

**Comment by jongogogo** [comment]
Looking at the API: https://docs.aws.amazon.com/cli/latest/reference/kms/schedule-key-deletion.html

It is during the action of deletion is where the time is added. So it means that the rule would flag the key when it is already being deleted already. Which make the tracking of when the action was executed tricky, because it doesn't show in the API (https://docs.aws.amazon.com/cli/latest/reference/kms/describe-key.html)

Would it make more sense to track that all or certain specified keys are not being deleted?

**Comment by 0xjjoyy** [comment]
Thank you for that link and details. Closing this as not currently applicable. Alternatives are detective controls [CloudWatch Alarms]( https://github.com/awslabs/aws-config-rules/issues/146) and [whitelist](https://github.com/awslabs/aws-config-rules/issues/147).
