### ISSUE TITLE
IAM_USER_USED_LAST_90_DAYS rule update request

### ISSUE THREAD

**Issue by fr-satoshi-yamanaka** [awslabs/aws-config-rules#219]
1. Even after deleting users from IAM console completely,  the deleted users are still in the evaluation scope and results returns IAM users in Resource ID format (AIDAxxxxxx. ). I am expecting that deleted users will be removed from evaluation preferably or marked NOT_APPLICABLE as written on code.
def is_applicable(configurationItem, event):
    check_defined(configurationItem, 'configurationItem')
    check_defined(event, 'event')
    status = configurationItem['configurationItemStatus']
    eventLeftScope = event['eventLeftScope']
    if status == 'ResourceDeleted':
        print("Resource Deleted, setting Compliance Status to NOT_APPLICABLE.")
    return (status == 'OK' or status == 'ResourceDiscovered') and not eventLeftScope

2. Can you please advise how i can modify python code in a way that IAM users with no logon history can be evaluated based on "Created time"? The published code returns NON-COMPLIANT against new IAM users without logon attempt. I want to evaluate a New IAM (no logon attempt so far) based on "Created time"

Thank you in advance.

**Comment by kritijha** [comment]
@fr-satoshi-yamanaka Thanks for creating this issue.

I deployed the rule at my end and upon some testing, I could see the following:
1. After deleting the users from the IAM console, they remain for some time in the evaluation scope before the Config service is able to pick up the change, i.e. deletion. Whether the change has been picked up by Config can also be verified by looking up the deleted IAM users in the 'Resources' tab in the AWS Config console.
    However, if you would trigger the rule manually, you'd be able to see that the results are as expected and the deleted resource(s) is excluded.

2. You could make use of the optional parameter 'NewUserCooldownInDays'. If the created date/time is newer than the (current date/time - NewUserCooldownInDays), COMPLIANT is returned for the resource. By default, this parameter is set to 7. You might be getting NON_COMPLIANT for your IAM users with no logon attempt due to them being older than 7 days.

I hope this helps. Let me know if the above scenarios do not match yours.

**Comment by jongogogo** [comment]
@fr-satoshi-yamanaka all good? I'll close the issue soon, if no additional questions.

**Comment by fr-satoshi-yamanaka** [comment]
Sorry for the delayed response. Appreciate your support. Noted. Please close the case
