### ISSUE TITLE
iam-mfa.py: how to correctly use?

### ISSUE THREAD

**Issue by rvandegrift** [awslabs/aws-config-rules#28]
Hello,

Is there a suggested deployment for iam-mfa.py?  I tried to deploy it as a triggered rule, but it never triggered on users adding an MFA token.  AWS Support says that MFA token changes don't count as config changes, so that makes some sense.  But then I'm not sure how the rule can work as described in RULES.md.

Support suggests deploying as a periodic rule, but not having per-user results undermines the usefulness of the rule.

Thanks for any suggestions,
Ross

**Comment by aaronkhoo** [comment]
Hi Ross, 

As you pointed out, MFA token changes don't trigger change notifications to AWS Config at the moment, so this rule has to be run as a periodic rule. Periodic rules can only report compliance against the Account, instead of individual resources (or users, in this case). 

We are considering some options to improve the experience in this area, particularly for periodic rules. Would love to hear feedback from users, of course. 

Thanks,

Aaron
