### ISSUE TITLE
python/iam-unused-keys.py shows compliant even for non-compliant iam-user.

### ISSUE THREAD

**Issue by smrutiranjantripathy** [awslabs/aws-config-rules#50]
This config rule shows compliant even for non-compliant resources.

**Comment by ShawnWarner7** [comment]
I have the same issue

**Comment by JPLachance** [comment]
Hello,

In https://github.com/awslabs/aws-config-rules/pull/71, I fixed the `iam-unused-keys.py` rule. The rule was broken due to some changes in AWS APIs. About merging `iam-unused-keys.py` and `iam-unused-user.py`, it looks like it was done in https://github.com/awslabs/aws-config-rules/pull/68.

Enjoy!
