### ISSUE TITLE
[Question] Should AWS Config Rules have side effects?

### ISSUE THREAD

**Issue by jghaines** [awslabs/aws-config-rules#56]
This is a "best practices" question. I have inherited a custom AWS Config Rule that implements auto tagging (doing a lookup to an external database).

This modifies the underlying resource. I'm wondering if this is considered bad practice. Also, can it result in the rule being re-triggered as it is a configuration change.

**Comment by gregjinkim** [comment]
One of the reasons AWS Config has not tackled this remediation feature yet is because they are wary of modifying your resources for you. But with a custom Config Rule, you own the resource and you own the remediation code; no worrying about whose fault it is if it does the wrong thing. 

Another reason AWS Config hasn't added the feature is because if the remediation code works, you won't see that your resource was ever NON_COMPLIANT. So if you have some infrastructure configuration set incorrectly, you might not realize it, since your rule corrects it for you. If you're willing to deal with that potential lack of visibility, it seems like a good rule feature.

**Comment by jongogogo** [comment]
Best practice: Use CloudWatch Events on Config (added recently) and trigger remediation.
